services:
  postgres:
      image: postgres:15-alpine
      container_name: postgres
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_USER: favour
        POSTGRES_DB: dataScrape
        POSTGRES_HOST_AUTH_METHOD: "trust"
      ports:
        - "5433:5432"